# Generated by Django 4.1.7 on 2023-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('idPokedex', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('generation', models.IntegerField()),
            ],
            options={
                'db_table': 'Pokemon',
            },
        ),
    ]
