# Generated by Django 4.1.7 on 2023-03-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('idType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='PokemonTypeHasType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pokemon_idPokedex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('Type_idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemontype')),
            ],
            options={
                'db_table': 'Pokemon_has_Type',
            },
        ),
    ]
